version: "3"

services:
  postgres:
    image: postgres:13.3
    container_name: postgres
    hostname: postgres
    expose:
      - "5432"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=support

  redis:
    image: redis
    container_name: suport_redis
    expose:
      - "6379"
    ports:
      - "6379:6379"

  django:
    &django
    build:
      context: .
    image: suport_django
    container_name: django
    expose:
      - "8000"
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    volumes:
      - ./:/app/
    env_file: .env
    command: "python manage.py runserver 0.0.0.0:8000"

  celeryworker:
    depends_on:
      - django
      - postgres
      - redis
    image: suport_django
    container_name: suport_celeryworker
    environment:
      - DEBUG=1
      - CELERY_BROKER_URL=redis://redis:6379
      - CELERY_BACKEND=redis://redis:6379
    command: sh -c "celery -A config worker -l info"
