# Generated by Django 4.0 on 2021-12-20 17:25

from django.db import migrations

from authentication.models import Role


def populate_roles_table(apps, schema_editor):
    for role in Role.ROLES_CHOICES:
        Role.objects.get_or_create(id=role[0])


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [migrations.RunPython(populate_roles_table)]
